INSERT INTO utente VALUES ('rbono', 'abcd@ef.it', '3.14', 0, '03/04/2014', NULL, false);
INSERT INTO utente VALUES ('nadia.c', 'nadia.corvino@gmail.com', 'qazwsxedc', -1, NULL, NULL, false);
INSERT INTO utente VALUES ('nico', 'niccolocantu@gmail.com', 'a', 4, NULL, NULL, true);
INSERT INTO utente VALUES ('tizio', 'tizio@gmail.com', 'a', -1, '06/17/2014', 'Pianeta di Re Kaio', false);
INSERT INTO utente VALUES ('al90', 'al90@msn.it', 'a', 0, NULL, 'la Terra di Al', false);
INSERT INTO utente VALUES ('bender', 'robot34@ct.it', 'a', -1, NULL, NULL, false);

INSERT INTO categoria VALUES (4, 'musica');
INSERT INTO categoria VALUES (5, 'informatica');
INSERT INTO categoria VALUES (6, 'videogames');
INSERT INTO categoria VALUES (7, 'calcio');
INSERT INTO categoria VALUES (8, 'sport');
INSERT INTO categoria VALUES (9, 'basket');
INSERT INTO categoria VALUES (10, 'viaggi');
INSERT INTO categoria VALUES (11, 'italia');

INSERT INTO sottocategoria VALUES (5, 6);
INSERT INTO sottocategoria VALUES (10, 11);
INSERT INTO sottocategoria VALUES (8, 9);
INSERT INTO sottocategoria VALUES (8, 7);

INSERT INTO domanda VALUES (34, 'Chi va al concerto di caparezza??', 'http://clubtenco.it/wp/wp-content/uploads/2014/11/24685.jpg', 'nico', 'una capa rezza', false, true);
INSERT INTO domanda VALUES (35, 'Dove vi piacerebbe di più andare al mare?', 'http://www.valentinapaiotta.it/wp-content/uploads/2015/03/vacanze.jpg', 'nico', 'vacanzeee!!!', true, true);
INSERT INTO domanda VALUES (36, 'Chi sono gli ultimi acquisti della Juve?', '', 'tizio', '', false, true);
INSERT INTO domanda VALUES (37, 'Quale tipo di videogiochi vi piacciono?', '', 'tizio', '', true, true);
INSERT INTO domanda VALUES (38, 'In che città si mangia meglio?', 'http://www.nextquotidiano.it/wp-content/uploads/2015/02/export-italia.jpg', 'al90', '', true, true);
INSERT INTO domanda VALUES (39, 'Su che canale del digitale posso seguire il basket italiano?', 'http://www.nbapassion.com/wp-content/uploads/2015/07/Lega-Basket-A.jpg', 'al90', '', false, true);
INSERT INTO domanda VALUES (40, 'Dove scarico la beta di Firefox?', '', 'bender', '', false, true);
INSERT INTO domanda VALUES (41, 'Mi consigliate una marca per il pc nuovo?', '', 'bender', '', false, true);

INSERT INTO argomentodomanda VALUES (34, 4);
INSERT INTO argomentodomanda VALUES (35, 10);
INSERT INTO argomentodomanda VALUES (35, 11);
INSERT INTO argomentodomanda VALUES (36, 7);
INSERT INTO argomentodomanda VALUES (37, 6);
INSERT INTO argomentodomanda VALUES (38, 11);
INSERT INTO argomentodomanda VALUES (39, 9);
INSERT INTO argomentodomanda VALUES (39, 11);
INSERT INTO argomentodomanda VALUES (40, 5);
INSERT INTO argomentodomanda VALUES (41, 5);

INSERT INTO interesse VALUES ('nico', 4);
INSERT INTO interesse VALUES ('nico', 6);
INSERT INTO interesse VALUES ('nico', 8);
INSERT INTO interesse VALUES ('nico', 9);
INSERT INTO interesse VALUES ('nico', 10);
INSERT INTO interesse VALUES ('nico', 7);
INSERT INTO interesse VALUES ('nico', 11);
INSERT INTO interesse VALUES ('tizio', 4);
INSERT INTO interesse VALUES ('tizio', 5);
INSERT INTO interesse VALUES ('tizio', 7);
INSERT INTO interesse VALUES ('tizio', 11);
INSERT INTO interesse VALUES ('tizio', 6);
INSERT INTO interesse VALUES ('al90', 9);
INSERT INTO interesse VALUES ('al90', 11);
INSERT INTO interesse VALUES ('bender', 5);
INSERT INTO interesse VALUES ('bender', 9);
INSERT INTO interesse VALUES ('bender', 6);
INSERT INTO interesse VALUES ('rbono', 5);
INSERT INTO interesse VALUES ('rbono', 6);
INSERT INTO interesse VALUES ('rbono', 8);
INSERT INTO interesse VALUES ('rbono', 10);
INSERT INTO interesse VALUES ('rbono', 11);
INSERT INTO interesse VALUES ('rbono', 9);
INSERT INTO interesse VALUES ('rbono', 7);
INSERT INTO interesse VALUES ('nadia.c', 4);
INSERT INTO interesse VALUES ('nadia.c', 10);
INSERT INTO interesse VALUES ('nadia.c', 11);

INSERT INTO rispostadiretta VALUES (16, 'tizio', 34, 'Buu Caparezza!!!', '2015-08-13 00:33:47.170591');
INSERT INTO rispostadiretta VALUES (17, 'bender', 39, 'e che ne so io?', '2015-08-13 00:49:12.674792');
INSERT INTO rispostadiretta VALUES (18, 'nico', 39, 'prova a cercare su google!', '2015-08-13 00:51:55.456469');
INSERT INTO rispostadiretta VALUES (19, 'nico', 39, 'credo sulla tv satellitare', '2015-08-13 00:53:11.90812');
INSERT INTO rispostadiretta VALUES (20, 'nico', 36, 'C. Ronaldo e Messi ahahahaah', '2015-08-13 00:54:00.377946');
INSERT INTO rispostadiretta VALUES (21, 'nico', 34, 'Sarai Bannato per questo!', '2015-08-13 00:54:28.395353');
INSERT INTO rispostadiretta VALUES (22, 'nico', 36, 'vogliamo Gotze!', '2015-08-13 00:55:33.557935');
INSERT INTO rispostadiretta VALUES (23, 'nico', 39, 'meglio il calcio però', '2015-08-13 01:04:33.476691');
INSERT INTO rispostadiretta VALUES (25, 'nico', 40, 'sul sito di Mozilla', '2015-08-13 01:11:33.555096');
INSERT INTO rispostadiretta VALUES (26, 'nadia.c', 34, 'Nessunooooooo bleaaahhh', '2015-08-15 17:40:21.12211');

INSERT INTO rispostasondaggio VALUES (25, 35, 'Italia - Toscana');
INSERT INTO rispostasondaggio VALUES (26, 35, 'Caraibi');
INSERT INTO rispostasondaggio VALUES (27, 35, 'Grecia');
INSERT INTO rispostasondaggio VALUES (28, 35, 'Hawaii');
INSERT INTO rispostasondaggio VALUES (29, 37, 'FPS');
INSERT INTO rispostasondaggio VALUES (30, 37, 'RPG');
INSERT INTO rispostasondaggio VALUES (31, 37, 'MMORPG');
INSERT INTO rispostasondaggio VALUES (32, 37, 'Arcade');
INSERT INTO rispostasondaggio VALUES (33, 37, 'Retrò');
INSERT INTO rispostasondaggio VALUES (34, 38, 'Milano');
INSERT INTO rispostasondaggio VALUES (35, 38, 'Firenze');
INSERT INTO rispostasondaggio VALUES (36, 38, 'Roma');

INSERT INTO votorisposta VALUES ('al90', 18, 'nico', true);
INSERT INTO votorisposta VALUES ('bender', 21, 'nico', true);
INSERT INTO votorisposta VALUES ('tizio', 19, 'nico', true);
INSERT INTO votorisposta VALUES ('bender', 22, 'nico', false);
INSERT INTO votorisposta VALUES ('tizio', 20, 'nico', true);
INSERT INTO votorisposta VALUES ('bender', 18, 'nico', false);
INSERT INTO votorisposta VALUES ('tizio', 21, 'nico', true);
INSERT INTO votorisposta VALUES ('al90', 23, 'nico', true);
INSERT INTO votorisposta VALUES ('nico', 16, 'tizio', false);
INSERT INTO votorisposta VALUES ('nico', 17, 'bender', false);
INSERT INTO votorisposta VALUES ('nico', 26, 'nadia.c', false);

INSERT INTO votosondaggio VALUES ('nico', 25, false, 35);
INSERT INTO votosondaggio VALUES ('tizio', 27, true, 35);
INSERT INTO votosondaggio VALUES ('tizio', 30, false, 37);
INSERT INTO votosondaggio VALUES ('al90', 35, false, 38);
INSERT INTO votosondaggio VALUES ('al90', 25, false, 35);
INSERT INTO votosondaggio VALUES ('bender', 29, false, 37);
INSERT INTO votosondaggio VALUES ('nico', 35, false, 38);
INSERT INTO votosondaggio VALUES ('nico', 32, true, 37);
INSERT INTO votosondaggio VALUES ('rbono', 35, false, 38);
INSERT INTO votosondaggio VALUES ('rbono', 32, true, 37);
INSERT INTO votosondaggio VALUES ('nadia.c', 35, false, 38);
INSERT INTO votosondaggio VALUES ('nadia.c', 28, false, 35);

SELECT pg_catalog.setval('cat_id', 11, true);
SELECT pg_catalog.setval('dom_id', 41, true);
SELECT pg_catalog.setval('rdir_id', 26, true);
SELECT pg_catalog.setval('rson_id', 36, true);
